# Your Solution# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: rithik11sit722part4.azurecr.io/book_catalog:latest
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
          - name: DATABASE_URL
            value: "postgresql://rithik11_sit722_part4_user:yLphWKpaYJQy1dL1vOdbV6l1IFpUEGW3@dpg-crhtla5umphs73c95g10-a.oregon-postgres.render.com/rithik11_sit722_part4"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: rithik11sit722part4.azurecr.io/inventory_management:latest
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
        env:
          - name: DATABASE_URL
            value: "postgresql://rithik11_sit722_part4_user:yLphWKpaYJQy1dL1vOdbV6l1IFpUEGW3@dpg-crhtla5umphs73c95g10-a.oregon-postgres.render.com/rithik11_sit722_part4"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001