name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set permissions for Creation.sh
      run: chmod +x ./scripts/Creation.sh


    - name: Verify Permissions (Optional)
      run: ls -l ./scripts/Creation.sh


    - name: Log in to Azure with service principal
      run: az login

    - name: Run Creation.sh
      run: ./scripts/Creation.sh

     - name: Extract Terraform Outputs
      id: tf_outputs
      run: |
        echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
        echo "ACR_USERNAME=$(terraform output -raw acr_admin_username)" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$(terraform output -raw acr_admin_password)" >> $GITHUB_ENV

    - name: Update GitHub Secrets
      uses: peter-evans/set-secret@v3
      with:
        secrets: |
          ACR_LOGIN_SERVER=${{ env.ACR_LOGIN_SERVER }}
          ACR_USERNAME=${{ env.ACR_USERNAME }}
          ACR_PASSWORD=${{ env.ACR_PASSWORD }}
    - name: Log in to Azure Container Registry
      run: echo ${{ env.ACR_PASSWORD }} | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ env.ACR_USERNAME }} --password-stdin

   
      
    

    
