name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set permissions for Creation.sh
      run: chmod +x ./scripts/Creation.sh

    - name: Verify Permissions (Optional)
      run: ls -l ./scripts/Creation.sh

    - name: Run Creation.sh
      run: ./scripts/Creation.sh

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: ./scripts/Creation.sh
