name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5  # Adjust to your desired version

      - name: Azure Login
        run: az login
      
      - name: Kube delete per
        run: chmod +x ./scripts/delete.sh

      
      - name: kube delete
        run: ./scripts/delete.sh 

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
